### ISSUE TITLE
Wire format change

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger#141] opened 2017-05-03 13:32 UTC
I would like to propose wire format change. There are two things in my mind:

* there is `uber` in headers: `uber-trace-Id` for span context and baggage prefix `uberctx`. This does not tell anything about jaeger. This could be changed to `jaeger-`
* `parentId` is redundant when using the new model

The change will be problematic due to a large deployment of mixed services (jaeger and zipkin thrift used simultaneously). 

I'm not sure how this could be done in the safest manner. Maybe implement new default inejector/extractor which would first extract/inject old and new headers and then after some time remove old headers.

This is also related to #121

**Comment by yurishkuro** [comment] 2017-05-03 14:08
-1

this is a duplicate of #121 and we already discussed that this change has practically no merits, just a cosmetic tweak, but is massively destructive on existing deployments.

**Comment by yurishkuro** [comment] 2017-07-01 21:50
Closing this, but re-open #121 for tracking in the future.

**Closed by yurishkuro** 2017-07-01 21:50 UTC
